alpha 0.1 translation

diff --git a/R/i18n/02_replace_in_code b/R/i18n/02_replace_in_code
--- a/R/i18n/02_replace_in_code
+++ b/R/i18n/02_replace_in_code
@@ -21,14 +21,11 @@ fi
 for file in $FILE; do
 	SOURCE=$file;
 	base=$(echo "${SOURCE%.*}" | sed "s/.*\///");
-	#DEST="../$(echo ${base} | sed "s/_i18n//").R";
-	DEST="../R/$(echo ${base} | sed "s/_i18n//").R";
+	DEST="../$(echo ${base} | sed "s/_i18n//").R";
 	if [[ -f $DEST ]]; then
 		while read -r line; do
-			#var=$(echo $line | sed "s/\ *<-\s*.*//");
-			#string=$(echo $line | sed "s/^.*<-\ *//");
-			var=$(echo $line | sed "s/\ *<-\s*.*//" | sed "s/\&/\\\&/g");
-			string=$(echo $line | sed "s/^.*<-\ *//" | sed "s/\&/\\\&/g");
+			var=$(echo $line | sed "s/\ *<-\s*.*//"  | sed "s/\]/\\\]/g"| sed "s/\[/\\\[/g" | sed "s/\&/\\\&/g");
+			string=$(echo $line | sed "s/^.*<-\ *//" | sed "s/\]/\\\]/g"| sed "s/\[/\\\[/g" | sed "s/\&/\\\&/g");
 			sed -i "s@${string}@${var}@g" "$DEST"
 		done < ${file}
 		echo "$DEST" done.
@@ -36,12 +33,24 @@ for file in $FILE; do
 		echo "$DEST" not found.
 		read -p "Apply translation file to every scripts in R? (y/N) " ans
 		if [[ $(echo $ans | grep -io "y") == "y" ]]; then
-			for f in ../R/*; do
+			for f in ../*; do
+				if [[ -d $f ]]; then
+					continue
+				fi
 				while read -r l; do
-					var=$(echo $l | sed "s/\ *<-\s*.*//" | sed "s/\&/\\\&/g");
-					string=$(echo $l | sed "s/^.*<-\ *//" | sed "s/\&/\\\&/g");
+					if [[ -z $l ]]; then
+						continue
+					fi
+					var=$(echo $l | sed "s/\ *<-\s*.*//"  | sed "s/\]/\\\]/g"| sed "s/\[/\\\[/g" | sed "s/\&/\\\&/g");
+					string=$(echo $l | sed "s/^.*<-\ *//" | sed "s/\]/\\\]/g"| sed "s/\[/\\\[/g" | sed "s/\&/\\\&/g");
 					sed -i "s@${string}@${var}@g" "$f"
+					if [[ $? -gt 0 && -n $l ]]; then
+						echo -e "ERROR on $l\n(var=$var ; string=$string)"
+						echo -e "  -> source file: $FILE"
+						echo -e "  -> destin file: $f"
+					fi
 				done < ${FILE}
+				echo " * translated $f"
 			done;
 		fi
 	fi;
